# Setup
name:         werphy'sblog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
mainurl: "https://werphy.github.io/werphy.igithub.io/"


# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
